Repository FRSOURCE/cypress-plugin-visual-regression-diff, pull requests merged in 2022-09, with the labels that each got.

#105 docs: info about scaling screenshot to viewport
  README.md
Labels: documentation

#114 fix: btoa error
  src/Base64.ts
  src/commands.ts
  src/support.ts
Labels: bug

#108 feat: img diff when resolution differs
  src/plugins.ts
Labels: enhancement
